apiVersion: v1
data:
{{- if .Values.conf.gitserverSSH }}
  id_rsa: {{ include "expandedString" (dict "str" .Values.conf.gitserverSSH.id_rsa "Files" .Files) | b64enc}}
  known_hosts: {{ include "expandedString" (dict "str" .Values.conf.gitserverSSH.known_hosts "Files" .Files) | b64enc }}
{{- end }}
kind: Secret
metadata:
  name: gitserver-ssh
type: Opaque
