{{if .Values.cluster.gitserver.ssh }}
apiVersion: v1
data:
{{- range $k, $v := .Values.cluster.gitserver.ssh }}
  {{ $k }}: {{ b64enc $v }}
{{- end }}
kind: Secret
metadata:
  name: gitserver-ssh
type: Opaque
{{end}}
