{{if .Values.cluster.gitserver.ssh }}
apiVersion: v1
data:
  id_rsa: {{ include "expandedString" (dict "str" .Values.cluster.gitserver.ssh.id_rsa "Files" .Files) | b64enc}}
  known_hosts: {{ include "expandedString" (dict "str" .Values.cluster.gitserver.ssh.known_hosts "Files" .Files) | b64enc }}
kind: Secret
metadata:
  name: gitserver-ssh
type: Opaque
{{end}}
