##---
# Source: sourcegraph/templates/config-file.ConfigMap.yaml
apiVersion: v1
data:
  config.json: |-
    {
      "appURL": "http://localhost:3080",
      "auth.allowSignup": true,
      "auth.provider": "builtin",
      "gitserverDiskSize": "200Gi",
      "httpNodePort": 30080,
      "indexedSearchDiskSize": "200Gi",
      "langservers": [
        {
          "language": "go"
        },
        {
          "language": "java"
        },
        {
          "language": "javascript"
        },
        {
          "language": "typescript"
        },
        {
          "language": "python"
        },
        {
          "language": "php"
        }
      ],
      "rbac": "enabled"
    }
kind: ConfigMap
metadata:
  name: config-file
