apiVersion: v1
kind: Service
metadata:
  labels:
    app: xlang-cs
    deploy: sourcegraph
  name: xlang-cs
spec:
  ports:
  - name: lsp
    port: 8080
    targetPort: lsp
  selector:
    app: xlang-cs
  type: ClusterIP
