apiVersion: v1
kind: Service
metadata:
  labels:
    app: xlang-dockerfile
    deploy: sourcegraph
  name: xlang-dockerfile
spec:
  ports:
  - name: lsp
    port: 8080
    targetPort: lsp
  selector:
    app: xlang-dockerfile
  type: ClusterIP
