apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    deploy: sourcegraph
  name: pod-tmp-gc
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: pod-tmp-gc
subjects:
- kind: ServiceAccount
  name: pod-tmp-gc
