apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: LSP server for Python (used for live requests).
  labels:
    deploy: sourcegraph
  name: xlang-python
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xlang-python
    spec:
      containers:
      - image: docker.sourcegraph.com/xlang-python:18329_2018-07-13_3bb3d65
        livenessProbe:
          initialDelaySeconds: 5
          tcpSocket:
            port: lsp
          timeoutSeconds: 5
        name: xlang-python
        ports:
        - containerPort: 2087
          name: lsp
        readinessProbe:
          tcpSocket:
            port: lsp
        resources:
          limits:
            cpu: 500m
            memory: 1G
          requests:
            cpu: 500m
            memory: 1G
