apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    category: rbac
    deploy: sourcegraph
  name: prometheus
  namespace: ns-sourcegraph
roleRef:
  apiGroup: ""
  kind: Role
  name: system:discovery
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: ns-sourcegraph
