apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    deploy: sourcegraph
    disk: pgsql
  name: pgsql
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  # AWS: Uncomment the three lines below and create a AWS EBS volume with the ID "sourcegraph-pgsql-prod"
  # See https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore
  #
  #awsElasticBlockStore:
  #  volumeID: sourcegraph-pgsql-prod
  #  fsType: ext4
  #
  # GCP: Uncomment the three lines below and create a GCE disk with the name "sourcegraph-pgsql-prod"
  # See https://kubernetes.io/docs/concepts/storage/volumes/#gcepersistentdisk 
  #
  #gcePersistentDisk:
  #  fsType: ext4
  #  pdName: sourcegraph-pgsql-prod
  #
  storageClassName: sourcegraph
