apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Postgres database for various data.
  labels:
    deploy: sourcegraph
  name: pgsql
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pgsql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pgsql
        group: backend
    spec:
      containers:
        - image: 'index.docker.io/sourcegraph/postgres-11.4:3.15.1@sha256:63090799b34b3115a387d96fe2227a37999d432b774a1d9b7966b8c5d81b56ad'
          livenessProbe:
            exec:
              command:
                - /liveness.sh
            initialDelaySeconds: 15
          name: pgsql
          ports:
            - containerPort: 5432
              name: pgsql
          readinessProbe:
            exec:
              command:
                - /ready.sh
          resources:
            limits:
              cpu: '4'
              memory: '2Gi'
            requests:
              cpu: '4'
              memory: '2Gi'
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /data
              name: disk
            - mountPath: /conf
              name: pgsql-conf
        - env:
            - name: DATA_SOURCE_NAME
              value: 'postgres://sg:@localhost:5432/?sslmode=disable'
          image: 'wrouesnel/postgres_exporter:v0.7.0@sha256:785c919627c06f540d515aac88b7966f352403f73e931e70dc2cbf783146a98b'
          name: pgsql-exporter
          resources:
            limits:
              cpu: '10m'
              memory: '50Mi'
            requests:
              cpu: '10m'
              memory: '50Mi'
          terminationMessagePolicy: FallbackToLogsOnError
      initContainers:
        - command:
            - sh
            - '-c'
            - 'if [ -d /data/pgdata-11 ]; then chmod 750 /data/pgdata-11; fi'
          image: 'sourcegraph/alpine:3.10@sha256:4d05cd5669726fc38823e92320659a6d1ef7879e62268adec5df658a0bacf65c'
          name: correct-data-dir-permissions
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /data
              name: disk
      securityContext:
        runAsUser: 0
      volumes:
        - name: disk
          persistentVolumeClaim:
            claimName: pgsql
        - configMap:
            defaultMode: 777
            name: pgsql-conf
          name: pgsql-conf
