{{- if not ( and (hasKey .Values.cluster "redis") (hasKey (index .Values.cluster "redis") "cache") ) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.cluster.storageClass.name }}
  name: redis-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
{{end -}}
