##---
# Source: sourcegraph/templates/config-file.ConfigMap.yaml
apiVersion: v1
data:
  config.json: |-
    {
      "appURL": "http://localhost:3080",
      "auth.allowSignup": true,
      "auth.providers": [
        {
          "type": "builtin"
        }
      ],
      "gitserverDiskSize": "200Gi",
      "httpNodePort": 30080,
      "indexedSearchDiskSize": "200Gi",
      "langservers": [
      ],
      "rbac": "enabled"
    }
kind: ConfigMap
metadata:
  name: config-file
