apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger-query
    deploy: jaeger
  name: jaeger-query
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: jaeger-query
  type: ClusterIP
