apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  labels:
    deploy: jaeger
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.16.0
  storage:
    type: memory
  ingress:
    enabled: false
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "4Gi"
      cpu: "2"
