apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger-cassandra
    deploy: jaeger
  name: jaeger-cassandra
spec:
  ports:
  - name: cql
    port: 9042
    targetPort: cql
  selector:
    app: jaeger-cassandra
  type: ClusterIP
