##---
# Source: sourcegraph/templates/config-file.ConfigMap.yaml
apiVersion: v1
data:
  config.json: |-
    {
      "appURL": "http://localhost:3080",
      "httpNodePort": 30080,
      "langservers": [
      ],
      "siteID": "123123123123",
      "useJaeger": true
    }
kind: ConfigMap
metadata:
  name: config-file
