cluster:
  storageClass:
    create: none
site: {
  "langservers": [
    {
      "language": "go",
    },
    {
      "language": "java",
    },
    {
      "language": "javascript",
    },
    {
      "language": "typescript",
    },
    {
      "language": "python",
    },
    {
      "language": "php",
    },
  ],
}
