apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    category: rbac
    deploy: sourcegraph
  name: frontend
roleRef:
  apiGroup: ""
  kind: Role
  name: frontend
subjects:
- kind: ServiceAccount
  name: frontend
