apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    category: rbac
    deploy: sourcegraph
  name: frontend
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
