apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '150m'
  labels:
    app: sourcegraph-frontend
    deploy: sourcegraph
  name: sourcegraph-frontend
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: sourcegraph-frontend
              servicePort: 30080
            path: /
