apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    category: rbac
    deploy: sourcegraph
  name: sourcegraph-frontend
  namespace: ns-sourcegraph
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: sourcegraph-frontend
  namespace: ns-sourcegraph
