apiVersion: v1
kind: Service
metadata:
  labels:
    app: xlang-java-bg
    deploy: xlang-java
  name: xlang-java-bg
spec:
  ports:
  - name: lsp
    port: 2088
    targetPort: lsp
  selector:
    app: xlang-java-bg
  type: ClusterIP
