##---
# Source: sourcegraph/templates/github-proxy/github-proxy.Deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: Rate-limiting proxy for the GitHub API.
  name: github-proxy
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: github-proxy
    spec:
      containers:
      - env:
        - name: CONFIG_FILE_HASH
          value: 2d50170ef9cbae09025b5aee5e9e11eb5f37f7c6115c81b350d8db5080f3db11
        - name: LOG_REQUESTS
          value: "true"
        - name: SOURCEGRAPH_CONFIG_FILE
          value: /etc/sourcegraph/config.json
        - name: SRC_PROF_HTTP
          value: :6060
        image: docker.sourcegraph.com/github-proxy:11943_2018-02-23_8bfb2ee
        name: github-proxy
        ports:
        - containerPort: 3180
          name: http
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 100m
            memory: 250M
        volumeMounts:
        - mountPath: /etc/sourcegraph
          name: sg-config
      - command:
        - /go/bin/agent-linux
        - --collector.host-port=jaeger-collector:14267
        image: docker.sourcegraph.com/jaeger-agent
        name: jaeger-agent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      securityContext:
        runAsUser: 0
      volumes:
      - configMap:
          defaultMode: 464
          name: config-file
        name: sg-config
