apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "6060"
    prometheus.io/scrape: "true"
  labels:
    app: gitserver-1
    deploy: sourcegraph
  name: gitserver-1
spec:
  ports:
  - name: rpc
    port: 3178
    targetPort: rpc
  selector:
    app: gitserver-1
  type: ClusterIP
