##---
# Source: sourcegraph/templates/indexer/indexer.Deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: Asynchronous indexing for global references.
  name: indexer
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
      - env:
        - name: CONFIG_FILE_HASH
          value: 2d50170ef9cbae09025b5aee5e9e11eb5f37f7c6115c81b350d8db5080f3db11
        - name: LSP_PROXY
          value: lsp-proxy:4388
        - name: PGDATABASE
          value: sg
        - name: PGHOST
          value: pgsql
        - name: PGPORT
          value: "5432"
        - name: PGSSLMODE
          value: disable
        - name: PGUSER
          value: sg
        - name: REDIS_MASTER_ENDPOINT
          value: redis-cache:6379
        - name: SOURCEGRAPH_CONFIG_FILE
          value: /etc/sourcegraph/config.json
        - name: SRC_GIT_SERVERS
          value: gitserver-1:3178
        - name: SRC_PROF_HTTP
          value: :6060
        image: docker.sourcegraph.com/indexer:16804_2018-06-11_32c5a47
        name: indexer
        ports:
        - containerPort: 3179
          name: http
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 100m
            memory: 250M
        volumeMounts:
        - mountPath: /etc/sourcegraph
          name: sg-config
      - command:
        - /go/bin/agent-linux
        - --collector.host-port=jaeger-collector:14267
        image: docker.sourcegraph.com/jaeger-agent
        name: jaeger-agent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      securityContext:
        runAsUser: 0
      volumes:
      - configMap:
          defaultMode: 464
          name: config-file
        name: sg-config
