apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Handles repository metadata (not Git data) lookups and updates from
      external code hosts and other similar services.
  labels:
    deploy: sourcegraph
  name: repo-updater
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: repo-updater
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: repo-updater
    spec:
      containers:
      - env:
        image: sourcegraph/repo-updater:insiders@sha256:38ae6c05f22b07a6109b837bb9297f9dde504df31e94b7152cfa88b5e7b78b84
        terminationMessagePolicy: FallbackToLogsOnError
        name: repo-updater
        ports:
        - containerPort: 3182
          name: http
        - containerPort: 6060
          name: debug
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi
      securityContext:
        runAsUser: 0
