apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Backend for replace operations.
  labels:
    deploy: sourcegraph
  name: replacer
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: replacer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: replacer
    spec:
      containers:
      - env:
        - name: REPLACER_CACHE_SIZE_MB
          value: "100000"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CACHE_DIR
          value: /mnt/cache/$(POD_NAME)
        image: index.docker.io/sourcegraph/replacer:3.14.0@sha256:8843d25125b8309623642fe22d9f4412e1c692ce3823b0bd2b5d924c4004808e
        terminationMessagePolicy: FallbackToLogsOnError
        name: replacer
        ports:
        - containerPort: 3185
          name: http
        - containerPort: 6060
          name: debug
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 500M
          requests:
            cpu: 500m
            memory: 500M
        volumeMounts:
        - mountPath: /mnt/cache
          name: cache-ssd
      - image: jaegertracing/jaeger-agent:1.16.0
        name: jaeger-agent
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        args:
          - --reporter.grpc.host-port=jaeger-collector:14250
          - --reporter.type=grpc
      volumes:
      - emptyDir: {}
        name: cache-ssd
