##---
# Source: sourcegraph/templates/symbols/symbols.Deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: Backend for symbols operations.
  name: symbols
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: symbols
    spec:
      containers:
      - env:
        - name: CONFIG_FILE_HASH
          value: 2adcaafa2b3e4ee8b701cf9aa4f6c8a8e465cb85d33a9c0483b20cb72370cade
        - name: SOURCEGRAPH_CONFIG_FILE
          value: /etc/sourcegraph/config.json
        - name: SRC_GIT_SERVERS
          value: gitserver-1:3178
        - name: SRC_PROF_HTTP
          value: :6060
        - name: SYMBOLS_CACHE_SIZE_MB
          value: "100000"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CACHE_DIR
          value: /mnt/cache/$(POD_NAME)
        image: docker.sourcegraph.com/symbols:13932_2018-04-09_b6883b9
        name: symbols
        ports:
        - containerPort: 3184
          name: http
        - containerPort: 6060
          name: debug
        resources:
          limits:
            cpu: "2"
            memory: "2G"
          requests:
            cpu: "500m"
            memory: "500M"
        volumeMounts:
        - mountPath: /etc/sourcegraph
          name: sg-config
        - mountPath: /mnt/cache
          name: cache-ssd
      securityContext:
        runAsUser: 0
      nodeSelector:
        beta.kubernetes.io/instance-type: m4.4xlarge
      volumes:
      - configMap:
          defaultMode: 464
          name: config-file
        name: sg-config
      - emptyDir: {}
        name: cache-ssd
