apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.opsconf.storageClass.name }}
  name: pgsql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
