apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Headless service that provides a stable network identity for the
      indexed-search stateful set.
    sourcegraph.prometheus/scrape: "true"
  labels:
    app: indexed-search
    deploy: sourcegraph
  name: indexed-search
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: indexed-search
  type: ClusterIP
