##---
# Source: sourcegraph/templates/storage-class.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: default
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: us-west1-a

