{{- if .Values.conf.useJaeger -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.opsconf.storageClass.name }}
  name: jaeger
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
{{ end -}}
