{{- if .Values.site.useAlertManager -}}
apiVersion: v1
data:
  config.yml: |
    {{- include "expandedString" (dict "str" .Values.site.alertmanagerConfig "Files" .Files) | nindent 4 }}
kind: ConfigMap
metadata:
  name: alertmanager
{{- end -}}
