apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Metrics/monitoring dashboards and alerts.
  labels:
    deploy: sourcegraph
  name: grafana
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: 'index.docker.io/sourcegraph/grafana:3.15.0@sha256:94ef3e7673d12e92487ca8966ab74b456f685edfc54fb163e1d49c7eaf064e70'
          name: grafana
          ports:
            - containerPort: 3370
              name: http
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
            requests:
              cpu: '100m'
              memory: '512Mi'
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: data
            - mountPath: /sg_config_grafana/provisioning/datasources
              name: config
      securityContext:
        runAsUser: 0
      serviceAccountName: grafana
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana
        - configMap:
            defaultMode: 777
            name: grafana
          name: config
