apiVersion: v1
# Whenever data changes you need to make sure all pods that reference config-file are restarted.
# You can run ./configure/config-file.sh to update the name of the config map to include a content hash.
# This script also updates all dependent files with the new name, which will force those services
# to restart when the new configuration is applied.
data:
  config.json: |
    {
      // Publicly accessible URL to web app (e.g., what you type into your browser).
      "appURL": "http://localhost:3080",

      // The authentication provider to use for identifying and signing in users. Only one entry is supported.
      //
      // The builtin auth provider with signup disallowed (shown below) means that after the initial site admin signs in, all other users must be invited.
      //
      // Other providers are documented here:
      // https://about.sourcegraph.com/docs/config/site#authproviders-array
      "auth.providers": [{"type": "builtin", "allowSignup": false}],
    }
kind: ConfigMap
metadata:
  labels:
    deploy: sourcegraph
  name: config-file-818d68ae92
