apiVersion: v1
kind: Service
metadata:
  labels:
    app: syntect-server
    deploy: sourcegraph
  name: syntect-server
  namespace: ns-sourcegraph
spec:
  ports:
  - name: http
    port: 9238
    targetPort: http
  selector:
    app: syntect-server
  type: ClusterIP
