apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Saved search query runner / notification service.
  labels:
    deploy: sourcegraph
  name: query-runner
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: query-runner
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: query-runner
    spec:
      containers:
      - env:
        image: index.docker.io/sourcegraph/query-runner:3.14.2@sha256:8a22d88a96435755fdcd25aac6b0f395e054c85b863adbfc5f78314b1c0c91a7
        terminationMessagePolicy: FallbackToLogsOnError
        name: query-runner
        ports:
        - containerPort: 3183
          name: http
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 500m
            memory: 1G
