apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Rate-limiting proxy for the GitHub API.
  labels:
    deploy: sourcegraph
  name: github-proxy
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: github-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: github-proxy
    spec:
      containers:
      - env:
        image: index.docker.io/sourcegraph/github-proxy:3.6.4@sha256:3914bf58612cd4dcd20fd1896fca7ee8efc4ec753d4265ca68582800fa1ca4cf
        terminationMessagePolicy: FallbackToLogsOnError
        name: github-proxy
        ports:
        - containerPort: 3180
          name: http
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 100m
            memory: 250M
      securityContext:
        runAsUser: 0
