apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Rate-limiting proxy for the GitHub API.
  labels:
    deploy: sourcegraph
  name: github-proxy
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: github-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: github-proxy
    spec:
      containers:
      - env:
        image: sourcegraph/github-proxy:3.4.5@sha256:576436acb7f36d145858d6cb5ed2ff1f7c97582ad4ac9d04bcebbc36482a2d91
        terminationMessagePolicy: FallbackToLogsOnError
        name: github-proxy
        ports:
        - containerPort: 3180
          name: http
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: 100m
            memory: 250M
      securityContext:
        runAsUser: 0
