{{- if and (hasKey .Values.site "prometheus") (ne .Values.site.rbac "disabled") -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: '{{.Release.Namespace}}-prometheus'
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: '{{.Release.Namespace}}'
{{ end -}}
