apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: query
    app.kubernetes.io/name: jaeger
    deploy: sourcegraph
  name: jaeger-query
spec:
  ports:
    - name: query-http
      port: 16686
      protocol: TCP
      targetPort: 16686
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/name: jaeger
  type: ClusterIP
