apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/name: jaeger
    deploy: sourcegraph
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/name: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: '16686'
        prometheus.io/scrape: 'true'
      labels:
        app: jaeger
        app.kubernetes.io/component: all-in-one
        app.kubernetes.io/name: jaeger
    spec:
      containers:
        - args:
            - '--memory.max-traces=20000'
          image: 'sourcegraph/jaeger-all-in-one:3.15.0@sha256:5fa54e0ef24d0c4afea3616b892e83210a8ab8d0906d4bc604bbfdc6c90df30f'
          name: jaeger
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 14269
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: '1'
              memory: '1G'
            requests:
              cpu: '500m'
              memory: '500M'
      securityContext:
        runAsUser: 0
