apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  labels:
    deploy: sourcegraph
    app: jaeger
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: query
spec:
  ports:
  - name: jaeger-query
    port: 16686
    protocol: TCP
    targetPort: 16686
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: query
  type: ClusterIP
