apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    deploy: sourcegraph
    app: elasticsearch
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: storage-backend
    app.kubernetes.io/part-of: jaeger
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: storage-backend
    app.kubernetes.io/part-of: jaeger
  ports:
  - port: 9200
    name: elasticsearch
  - port: 9300
    name: transport
