apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9090"
    sourcegraph.prometheus/federate: "true"
  labels:
    app: lsif-server
    deploy: sourcegraph
  name: lsif-server
spec:
  ports:
    # HTTP API and health endpoint
  - name: server
    port: 3186
    targetPort: server
    # Health endpoint
  - name: worker
    port: 3187
    targetPort: worker
    # For metrics and federation  
  - name: prometheus
    port: 9090
    targetPort: prometheus
  selector:
    app: lsif-server
  type: ClusterIP
