apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9090"
    sourcegraph.prometheus/federate: "true"
  labels:
    app: lsif-server
    deploy: sourcegraph
  name: lsif-server
spec:
  ports:
  - name: server
    port: 3186
    targetPort: server
  - name: dump-manager
    port: 3187
    targetPort: dump-manager
  - name: dump-processor
    port: 3188
    targetPort: dump-processor
  - name: prometheus
    port: 9090
    targetPort: prometheus
  selector:
    app: lsif-server
  type: ClusterIP
