apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9090"
    sourcegraph.prometheus/federate: "true"
  labels:
    app: lsif-worker
    deploy: sourcegraph
  name: lsif-worker
spec:
  ports:
    # For health endpoint ONLY
  - name: worker
    port: 3187
    targetPort: worker
    # For metrics and federation
  - name: prometheus
    port: 9090
    targetPort: prometheus
  selector:
    app: lsif-worker
  type: ClusterIP
