##---
# Source: sourcegraph/templates/xlang/php/xlang-php.Deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: LSP server for PHP.
  name: xlang-php
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xlang-php
    spec:
      containers:
      - env:
        - name: COMPOSER_AUTH
          value: '{"github-oauth": {"github.com": ""}}'
        image: docker.sourcegraph.com/xlang-php:00006_2017-11-09_6ead48c
        name: xlang-php
        ports:
        - containerPort: 2088
          name: lsp
        resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "500m"
            memory: "2Gi"
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - emptyDir: {}
        name: tmp
